/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAvailablePizzaIngredientsResponse from '../model/GetAvailablePizzaIngredientsResponse';

/**
* PizzaIngredient service.
* @module api/PizzaIngredientApi
* @version 1.0
*/
export default class PizzaIngredientApi {

    /**
    * Constructs a new PizzaIngredientApi. 
    * @alias module:api/PizzaIngredientApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Number} cityId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetAvailablePizzaIngredientsResponse} and HTTP response
     */
    getCityAvailableIngredientsWithHttpInfo(cityId) {
      let postBody = null;
      // verify the required parameter 'cityId' is set
      if (cityId === undefined || cityId === null) {
        throw new Error("Missing the required parameter 'cityId' when calling getCityAvailableIngredients");
      }

      let pathParams = {
        'cityId': cityId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAvailablePizzaIngredientsResponse;
      return this.apiClient.callApi(
        '/v1/pizza/ingredient/city/{cityId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} cityId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetAvailablePizzaIngredientsResponse}
     */
    getCityAvailableIngredients(cityId) {
      return this.getCityAvailableIngredientsWithHttpInfo(cityId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
