/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BonusProductData from './BonusProductData';

/**
 * The BonusProducts model module.
 * @module model/BonusProducts
 * @version 1.0
 */
class BonusProducts {
    /**
     * Constructs a new <code>BonusProducts</code>.
     * @alias module:model/BonusProducts
     * @param offerType {module:model/BonusProducts.OfferTypeEnum} 
     */
    constructor(offerType) { 
        
        BonusProducts.initialize(this, offerType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, offerType) { 
        obj['offerType'] = offerType;
    }

    /**
     * Constructs a <code>BonusProducts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BonusProducts} obj Optional instance to populate.
     * @return {module:model/BonusProducts} The populated <code>BonusProducts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BonusProducts();

            if (data.hasOwnProperty('bonusProducts')) {
                obj['bonusProducts'] = ApiClient.convertToType(data['bonusProducts'], [BonusProductData]);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('offerType')) {
                obj['offerType'] = ApiClient.convertToType(data['offerType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/BonusProductData>} bonusProducts
 */
BonusProducts.prototype['bonusProducts'] = undefined;

/**
 * @member {Number} amount
 */
BonusProducts.prototype['amount'] = undefined;

/**
 * @member {module:model/BonusProducts.OfferTypeEnum} offerType
 */
BonusProducts.prototype['offerType'] = undefined;





/**
 * Allowed values for the <code>offerType</code> property.
 * @enum {String}
 * @readonly
 */
BonusProducts['OfferTypeEnum'] = {

    /**
     * value: "MONEY_DISCOUNT"
     * @const
     */
    "MONEY_DISCOUNT": "MONEY_DISCOUNT",

    /**
     * value: "PERCENT_DISCOUNT"
     * @const
     */
    "PERCENT_DISCOUNT": "PERCENT_DISCOUNT",

    /**
     * value: "BONUS_PRODUCTS"
     * @const
     */
    "BONUS_PRODUCTS": "BONUS_PRODUCTS"
};



export default BonusProducts;

