/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartSimpleProductRequest model module.
 * @module model/CartSimpleProductRequest
 * @version 1.0
 */
class CartSimpleProductRequest {
    /**
     * Constructs a new <code>CartSimpleProductRequest</code>.
     * @alias module:model/CartSimpleProductRequest
     */
    constructor() { 
        
        CartSimpleProductRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CartSimpleProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartSimpleProductRequest} obj Optional instance to populate.
     * @return {module:model/CartSimpleProductRequest} The populated <code>CartSimpleProductRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartSimpleProductRequest();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} productId
 */
CartSimpleProductRequest.prototype['productId'] = undefined;

/**
 * @member {Number} amount
 */
CartSimpleProductRequest.prototype['amount'] = undefined;






export default CartSimpleProductRequest;

