/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartCustomerRequest model module.
 * @module model/CartCustomerRequest
 * @version 1.0
 */
class CartCustomerRequest {
    /**
     * Constructs a new <code>CartCustomerRequest</code>.
     * @alias module:model/CartCustomerRequest
     * @param phone {String} 
     */
    constructor(phone) { 
        
        CartCustomerRequest.initialize(this, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone) { 
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>CartCustomerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartCustomerRequest} obj Optional instance to populate.
     * @return {module:model/CartCustomerRequest} The populated <code>CartCustomerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartCustomerRequest();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} phone
 */
CartCustomerRequest.prototype['phone'] = undefined;

/**
 * @member {String} email
 */
CartCustomerRequest.prototype['email'] = undefined;

/**
 * @member {String} fullName
 */
CartCustomerRequest.prototype['fullName'] = undefined;






export default CartCustomerRequest;

