/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartCheckoutResponse model module.
 * @module model/CartCheckoutResponse
 * @version 1.0
 */
class CartCheckoutResponse {
    /**
     * Constructs a new <code>CartCheckoutResponse</code>.
     * @alias module:model/CartCheckoutResponse
     */
    constructor() { 
        
        CartCheckoutResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CartCheckoutResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartCheckoutResponse} obj Optional instance to populate.
     * @return {module:model/CartCheckoutResponse} The populated <code>CartCheckoutResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartCheckoutResponse();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('redirectLink')) {
                obj['redirectLink'] = ApiClient.convertToType(data['redirectLink'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} orderId
 */
CartCheckoutResponse.prototype['orderId'] = undefined;

/**
 * @member {String} redirectLink
 */
CartCheckoutResponse.prototype['redirectLink'] = undefined;






export default CartCheckoutResponse;

