/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CashPaymentAllOf model module.
 * @module model/CashPaymentAllOf
 * @version 1.0
 */
class CashPaymentAllOf {
    /**
     * Constructs a new <code>CashPaymentAllOf</code>.
     * @alias module:model/CashPaymentAllOf
     */
    constructor() { 
        
        CashPaymentAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CashPaymentAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashPaymentAllOf} obj Optional instance to populate.
     * @return {module:model/CashPaymentAllOf} The populated <code>CashPaymentAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashPaymentAllOf();

            if (data.hasOwnProperty('changeFor')) {
                obj['changeFor'] = ApiClient.convertToType(data['changeFor'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} changeFor
 */
CashPaymentAllOf.prototype['changeFor'] = undefined;






export default CashPaymentAllOf;

