/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CashlessPaymentAllOf from './CashlessPaymentAllOf';
import Payment from './Payment';

/**
 * The CashlessPayment model module.
 * @module model/CashlessPayment
 * @version 1.0
 */
class CashlessPayment {
    /**
     * Constructs a new <code>CashlessPayment</code>.
     * @alias module:model/CashlessPayment
     * @extends module:model/Payment
     * @implements module:model/Payment
     * @implements module:model/CashlessPaymentAllOf
     * @param type {String} 
     */
    constructor(type) { 
        Payment.initialize(this, type);CashlessPaymentAllOf.initialize(this);
        CashlessPayment.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
    }

    /**
     * Constructs a <code>CashlessPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashlessPayment} obj Optional instance to populate.
     * @return {module:model/CashlessPayment} The populated <code>CashlessPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashlessPayment();
            Payment.constructFromObject(data, obj);
            Payment.constructFromObject(data, obj);
            CashlessPaymentAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CashlessPayment.PaymentMethodEnum} paymentMethod
 */
CashlessPayment.prototype['paymentMethod'] = undefined;


// Implement Payment interface:
/**
 * @member {String} type
 */
Payment.prototype['type'] = undefined;
// Implement CashlessPaymentAllOf interface:
/**
 * @member {module:model/CashlessPaymentAllOf.PaymentMethodEnum} paymentMethod
 */
CashlessPaymentAllOf.prototype['paymentMethod'] = undefined;



/**
 * Allowed values for the <code>paymentMethod</code> property.
 * @enum {String}
 * @readonly
 */
CashlessPayment['PaymentMethodEnum'] = {

    /**
     * value: "YOOKASSA"
     * @const
     */
    "YOOKASSA": "YOOKASSA"
};



export default CashlessPayment;

