/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CashPaymentAllOf from './CashPaymentAllOf';
import Payment from './Payment';

/**
 * The CashPayment model module.
 * @module model/CashPayment
 * @version 1.0
 */
class CashPayment {
    /**
     * Constructs a new <code>CashPayment</code>.
     * @alias module:model/CashPayment
     * @extends module:model/Payment
     * @implements module:model/Payment
     * @implements module:model/CashPaymentAllOf
     * @param type {String} 
     */
    constructor(type) { 
        Payment.initialize(this, type);CashPaymentAllOf.initialize(this);
        CashPayment.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
    }

    /**
     * Constructs a <code>CashPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashPayment} obj Optional instance to populate.
     * @return {module:model/CashPayment} The populated <code>CashPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashPayment();
            Payment.constructFromObject(data, obj);
            Payment.constructFromObject(data, obj);
            CashPaymentAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('changeFor')) {
                obj['changeFor'] = ApiClient.convertToType(data['changeFor'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} changeFor
 */
CashPayment.prototype['changeFor'] = undefined;


// Implement Payment interface:
/**
 * @member {String} type
 */
Payment.prototype['type'] = undefined;
// Implement CashPaymentAllOf interface:
/**
 * @member {Number} changeFor
 */
CashPaymentAllOf.prototype['changeFor'] = undefined;




export default CashPayment;

