/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductCategoryResponse from './ProductCategoryResponse';
import SimpleProductResponse from './SimpleProductResponse';

/**
 * The CategorizedProducts model module.
 * @module model/CategorizedProducts
 * @version 1.0
 */
class CategorizedProducts {
    /**
     * Constructs a new <code>CategorizedProducts</code>.
     * @alias module:model/CategorizedProducts
     */
    constructor() { 
        
        CategorizedProducts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CategorizedProducts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategorizedProducts} obj Optional instance to populate.
     * @return {module:model/CategorizedProducts} The populated <code>CategorizedProducts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategorizedProducts();

            if (data.hasOwnProperty('category')) {
                obj['category'] = ProductCategoryResponse.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [SimpleProductResponse]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProductCategoryResponse} category
 */
CategorizedProducts.prototype['category'] = undefined;

/**
 * @member {Array.<module:model/SimpleProductResponse>} products
 */
CategorizedProducts.prototype['products'] = undefined;






export default CategorizedProducts;

