/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckCartResponse model module.
 * @module model/CheckCartResponse
 * @version 1.0
 */
class CheckCartResponse {
    /**
     * Constructs a new <code>CheckCartResponse</code>.
     * @alias module:model/CheckCartResponse
     */
    constructor() { 
        
        CheckCartResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckCartResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckCartResponse} obj Optional instance to populate.
     * @return {module:model/CheckCartResponse} The populated <code>CheckCartResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckCartResponse();

            if (data.hasOwnProperty('totalSum')) {
                obj['totalSum'] = ApiClient.convertToType(data['totalSum'], 'Number');
            }
            if (data.hasOwnProperty('deliveryPrice')) {
                obj['deliveryPrice'] = ApiClient.convertToType(data['deliveryPrice'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} totalSum
 */
CheckCartResponse.prototype['totalSum'] = undefined;

/**
 * @member {Number} deliveryPrice
 */
CheckCartResponse.prototype['deliveryPrice'] = undefined;






export default CheckCartResponse;

