/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
// import OneOfPizzaSimple from './OneOfPizzaSimple';
import ProductsRequest from './ProductsRequest';

/**
 * The CheckCartRequest model module.
 * @module model/CheckCartRequest
 * @version 1.0
 */
class CheckCartRequest {
    /**
     * Constructs a new <code>CheckCartRequest</code>.
     * @alias module:model/CheckCartRequest
     * @param products {module:model/ProductsRequest}
     */
    constructor(products) {

        CheckCartRequest.initialize(this, products);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, products) {
        obj['products'] = products;
    }

    /**
     * Constructs a <code>CheckCartRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckCartRequest} obj Optional instance to populate.
     * @return {module:model/CheckCartRequest} The populated <code>CheckCartRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckCartRequest();

            if (data.hasOwnProperty('cityId')) {
                obj['cityId'] = ApiClient.convertToType(data['cityId'], 'Number');
            }
            if (data.hasOwnProperty('promoCode')) {
                obj['promoCode'] = ApiClient.convertToType(data['promoCode'], 'String');
            }
            if (data.hasOwnProperty('addressId')) {
                obj['addressId'] = ApiClient.convertToType(data['addressId'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ProductsRequest.constructFromObject(data['products']);
            }
            if (data.hasOwnProperty('bonusProducts')) {
                obj['bonusProducts'] = ApiClient.convertToType(data['bonusProducts'], [OneOfPizzaSimple]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cityId
 */
CheckCartRequest.prototype['cityId'] = undefined;

/**
 * @member {String} promoCode
 */
CheckCartRequest.prototype['promoCode'] = undefined;

/**
 * @member {String} addressId
 */
CheckCartRequest.prototype['addressId'] = undefined;

/**
 * @member {module:model/ProductsRequest} products
 */
CheckCartRequest.prototype['products'] = undefined;

/**
 * @member {Array.<module:model/OneOfPizzaSimple>} bonusProducts
 */
CheckCartRequest.prototype['bonusProducts'] = undefined;






export default CheckCartRequest;

