/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartCustomerRequest from './CartCustomerRequest';
// import OneOfCashPaymentCashlessPayment from './OneOfCashPaymentCashlessPayment';
// import OneOfPizzaSimple from './OneOfPizzaSimple';
import ProductsRequest from './ProductsRequest';

/**
 * The CheckoutRequest model module.
 * @module model/CheckoutRequest
 * @version 1.0
 */
class CheckoutRequest {
    /**
     * Constructs a new <code>CheckoutRequest</code>.
     * @alias module:model/CheckoutRequest
     * @param addressId {String}
     * @param customer {module:model/CartCustomerRequest}
     * @param payment {module:model/OneOfCashPaymentCashlessPayment}
     * @param products {module:model/ProductsRequest}
     */
    constructor(addressId, customer, payment, products) {

        CheckoutRequest.initialize(this, addressId, customer, payment, products);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, addressId, customer, payment, products) {
        obj['addressId'] = addressId;
        obj['customer'] = customer;
        obj['payment'] = payment;
        obj['products'] = products;
    }

    /**
     * Constructs a <code>CheckoutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckoutRequest} obj Optional instance to populate.
     * @return {module:model/CheckoutRequest} The populated <code>CheckoutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckoutRequest();

            if (data.hasOwnProperty('cityId')) {
                obj['cityId'] = ApiClient.convertToType(data['cityId'], 'Number');
            }
            if (data.hasOwnProperty('promoCode')) {
                obj['promoCode'] = ApiClient.convertToType(data['promoCode'], 'String');
            }
            if (data.hasOwnProperty('addressId')) {
                obj['addressId'] = ApiClient.convertToType(data['addressId'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = CartCustomerRequest.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = ApiClient.convertToType(data['payment'], OneOfCashPaymentCashlessPayment);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ProductsRequest.constructFromObject(data['products']);
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('bonusProducts')) {
                obj['bonusProducts'] = ApiClient.convertToType(data['bonusProducts'], [OneOfPizzaSimple]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cityId
 */
CheckoutRequest.prototype['cityId'] = undefined;

/**
 * @member {String} promoCode
 */
CheckoutRequest.prototype['promoCode'] = undefined;

/**
 * @member {String} addressId
 */
CheckoutRequest.prototype['addressId'] = undefined;

/**
 * @member {module:model/CartCustomerRequest} customer
 */
CheckoutRequest.prototype['customer'] = undefined;

/**
 * @member {module:model/OneOfCashPaymentCashlessPayment} payment
 */
CheckoutRequest.prototype['payment'] = undefined;

/**
 * @member {module:model/ProductsRequest} products
 */
CheckoutRequest.prototype['products'] = undefined;

/**
 * @member {String} note
 */
CheckoutRequest.prototype['note'] = undefined;

/**
 * @member {Array.<module:model/OneOfPizzaSimple>} bonusProducts
 */
CheckoutRequest.prototype['bonusProducts'] = undefined;






export default CheckoutRequest;

