/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeliveryThresholdPriceResponse model module.
 * @module model/DeliveryThresholdPriceResponse
 * @version 1.0
 */
class DeliveryThresholdPriceResponse {
    /**
     * Constructs a new <code>DeliveryThresholdPriceResponse</code>.
     * @alias module:model/DeliveryThresholdPriceResponse
     */
    constructor() { 
        
        DeliveryThresholdPriceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeliveryThresholdPriceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeliveryThresholdPriceResponse} obj Optional instance to populate.
     * @return {module:model/DeliveryThresholdPriceResponse} The populated <code>DeliveryThresholdPriceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryThresholdPriceResponse();

            if (data.hasOwnProperty('orderSumThreshold')) {
                obj['orderSumThreshold'] = ApiClient.convertToType(data['orderSumThreshold'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} orderSumThreshold
 */
DeliveryThresholdPriceResponse.prototype['orderSumThreshold'] = undefined;

/**
 * @member {Number} price
 */
DeliveryThresholdPriceResponse.prototype['price'] = undefined;






export default DeliveryThresholdPriceResponse;

