/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeliveryThresholdPriceResponse from './DeliveryThresholdPriceResponse';

/**
 * The DeliveryPricesResponse model module.
 * @module model/DeliveryPricesResponse
 * @version 1.0
 */
class DeliveryPricesResponse {
    /**
     * Constructs a new <code>DeliveryPricesResponse</code>.
     * @alias module:model/DeliveryPricesResponse
     */
    constructor() { 
        
        DeliveryPricesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeliveryPricesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeliveryPricesResponse} obj Optional instance to populate.
     * @return {module:model/DeliveryPricesResponse} The populated <code>DeliveryPricesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryPricesResponse();

            if (data.hasOwnProperty('defaultPrice')) {
                obj['defaultPrice'] = ApiClient.convertToType(data['defaultPrice'], 'Number');
            }
            if (data.hasOwnProperty('thresholdPrices')) {
                obj['thresholdPrices'] = ApiClient.convertToType(data['thresholdPrices'], [DeliveryThresholdPriceResponse]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} defaultPrice
 */
DeliveryPricesResponse.prototype['defaultPrice'] = undefined;

/**
 * @member {Array.<module:model/DeliveryThresholdPriceResponse>} thresholdPrices
 */
DeliveryPricesResponse.prototype['thresholdPrices'] = undefined;






export default DeliveryPricesResponse;

