/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PizzaIngredient from './PizzaIngredient';

/**
 * The GetAvailablePizzaIngredientsResponse model module.
 * @module model/GetAvailablePizzaIngredientsResponse
 * @version 1.0
 */
class GetAvailablePizzaIngredientsResponse {
    /**
     * Constructs a new <code>GetAvailablePizzaIngredientsResponse</code>.
     * @alias module:model/GetAvailablePizzaIngredientsResponse
     */
    constructor() { 
        
        GetAvailablePizzaIngredientsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAvailablePizzaIngredientsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAvailablePizzaIngredientsResponse} obj Optional instance to populate.
     * @return {module:model/GetAvailablePizzaIngredientsResponse} The populated <code>GetAvailablePizzaIngredientsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAvailablePizzaIngredientsResponse();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PizzaIngredient]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PizzaIngredient>} items
 */
GetAvailablePizzaIngredientsResponse.prototype['items'] = undefined;






export default GetAvailablePizzaIngredientsResponse;

