/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeliveryPricesResponse from './DeliveryPricesResponse';

/**
 * The GetCityInfoResponse model module.
 * @module model/GetCityInfoResponse
 * @version 1.0
 */
class GetCityInfoResponse {
    /**
     * Constructs a new <code>GetCityInfoResponse</code>.
     * @alias module:model/GetCityInfoResponse
     */
    constructor() { 
        
        GetCityInfoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCityInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCityInfoResponse} obj Optional instance to populate.
     * @return {module:model/GetCityInfoResponse} The populated <code>GetCityInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCityInfoResponse();

            if (data.hasOwnProperty('cityId')) {
                obj['cityId'] = ApiClient.convertToType(data['cityId'], 'Number');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('zoneId')) {
                obj['zoneId'] = ApiClient.convertToType(data['zoneId'], 'String');
            }
            if (data.hasOwnProperty('deliveryPrices')) {
                obj['deliveryPrices'] = DeliveryPricesResponse.constructFromObject(data['deliveryPrices']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cityId
 */
GetCityInfoResponse.prototype['cityId'] = undefined;

/**
 * @member {String} displayName
 */
GetCityInfoResponse.prototype['displayName'] = undefined;

/**
 * @member {String} zoneId
 */
GetCityInfoResponse.prototype['zoneId'] = undefined;

/**
 * @member {module:model/DeliveryPricesResponse} deliveryPrices
 */
GetCityInfoResponse.prototype['deliveryPrices'] = undefined;






export default GetCityInfoResponse;

