/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CategorizedProducts from './CategorizedProducts';
import PizzaProductResponse from './PizzaProductResponse';

/**
 * The GetProductCatalogResponse model module.
 * @module model/GetProductCatalogResponse
 * @version 1.0
 */
class GetProductCatalogResponse {
    /**
     * Constructs a new <code>GetProductCatalogResponse</code>.
     * @alias module:model/GetProductCatalogResponse
     */
    constructor() { 
        
        GetProductCatalogResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProductCatalogResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductCatalogResponse} obj Optional instance to populate.
     * @return {module:model/GetProductCatalogResponse} The populated <code>GetProductCatalogResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProductCatalogResponse();

            if (data.hasOwnProperty('pizza')) {
                obj['pizza'] = ApiClient.convertToType(data['pizza'], [PizzaProductResponse]);
            }
            if (data.hasOwnProperty('simple')) {
                obj['simple'] = ApiClient.convertToType(data['simple'], [CategorizedProducts]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PizzaProductResponse>} pizza
 */
GetProductCatalogResponse.prototype['pizza'] = undefined;

/**
 * @member {Array.<module:model/CategorizedProducts>} simple
 */
GetProductCatalogResponse.prototype['simple'] = undefined;






export default GetProductCatalogResponse;

