/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PizzaBonusAllOf model module.
 * @module model/PizzaBonusAllOf
 * @version 1.0
 */
class PizzaBonusAllOf {
    /**
     * Constructs a new <code>PizzaBonusAllOf</code>.
     * @alias module:model/PizzaBonusAllOf
     */
    constructor() { 
        
        PizzaBonusAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PizzaBonusAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PizzaBonusAllOf} obj Optional instance to populate.
     * @return {module:model/PizzaBonusAllOf} The populated <code>PizzaBonusAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PizzaBonusAllOf();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('sizeGroup')) {
                obj['sizeGroup'] = ApiClient.convertToType(data['sizeGroup'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} productId
 */
PizzaBonusAllOf.prototype['productId'] = undefined;

/**
 * @member {Number} sizeGroup
 */
PizzaBonusAllOf.prototype['sizeGroup'] = undefined;






export default PizzaBonusAllOf;

