/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PizzaAllOf from './PizzaAllOf';

/**
 * The Pizza model module.
 * @module model/Pizza
 * @version 1.0
 */
class Pizza {
    /**
     * Constructs a new <code>Pizza</code>.
     * @alias module:model/Pizza
     * @implements module:model/PizzaAllOf
     */
    constructor() { 
        PizzaAllOf.initialize(this);
        Pizza.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Pizza</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Pizza} obj Optional instance to populate.
     * @return {module:model/Pizza} The populated <code>Pizza</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pizza();
            PizzaAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('sizeGroup')) {
                obj['sizeGroup'] = ApiClient.convertToType(data['sizeGroup'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} productId
 */
Pizza.prototype['productId'] = undefined;

/**
 * @member {Number} price
 */
Pizza.prototype['price'] = undefined;

/**
 * @member {Number} sizeGroup
 */
Pizza.prototype['sizeGroup'] = undefined;


// Implement PizzaAllOf interface:
/**
 * @member {Number} productId
 */
PizzaAllOf.prototype['productId'] = undefined;
/**
 * @member {Number} price
 */
PizzaAllOf.prototype['price'] = undefined;
/**
 * @member {Number} sizeGroup
 */
PizzaAllOf.prototype['sizeGroup'] = undefined;




export default Pizza;

