/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PizzaVariation model module.
 * @module model/PizzaVariation
 * @version 1.0
 */
class PizzaVariation {
    /**
     * Constructs a new <code>PizzaVariation</code>.
     * @alias module:model/PizzaVariation
     */
    constructor() { 
        
        PizzaVariation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PizzaVariation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PizzaVariation} obj Optional instance to populate.
     * @return {module:model/PizzaVariation} The populated <code>PizzaVariation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PizzaVariation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('sizeGroup')) {
                obj['sizeGroup'] = ApiClient.convertToType(data['sizeGroup'], 'Number');
            }
            if (data.hasOwnProperty('doughType')) {
                obj['doughType'] = ApiClient.convertToType(data['doughType'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], 'String');
            }
            if (data.hasOwnProperty('boardsAvailable')) {
                obj['boardsAvailable'] = ApiClient.convertToType(data['boardsAvailable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PizzaVariation.prototype['id'] = undefined;

/**
 * @member {module:model/PizzaVariation.SizeGroupEnum} sizeGroup
 */
PizzaVariation.prototype['sizeGroup'] = undefined;

/**
 * @member {module:model/PizzaVariation.DoughTypeEnum} doughType
 */
PizzaVariation.prototype['doughType'] = undefined;

/**
 * @member {Number} price
 */
PizzaVariation.prototype['price'] = undefined;

/**
 * @member {String} imageUrl
 */
PizzaVariation.prototype['imageUrl'] = undefined;

/**
 * @member {String} meta
 */
PizzaVariation.prototype['meta'] = undefined;

/**
 * @member {Boolean} boardsAvailable
 */
PizzaVariation.prototype['boardsAvailable'] = undefined;





/**
 * Allowed values for the <code>sizeGroup</code> property.
 * @enum {Number}
 * @readonly
 */
PizzaVariation['SizeGroupEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3
};


/**
 * Allowed values for the <code>doughType</code> property.
 * @enum {String}
 * @readonly
 */
PizzaVariation['DoughTypeEnum'] = {

    /**
     * value: "TRADITIONAL"
     * @const
     */
    "TRADITIONAL": "TRADITIONAL",

    /**
     * value: "THIN"
     * @const
     */
    "THIN": "THIN"
};



export default PizzaVariation;

