/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PromoOffersRequest model module.
 * @module model/PromoOffersRequest
 * @version 1.0
 */
class PromoOffersRequest {
    /**
     * Constructs a new <code>PromoOffersRequest</code>.
     * @alias module:model/PromoOffersRequest
     * @param promocode {String} 
     */
    constructor(promocode) { 
        
        PromoOffersRequest.initialize(this, promocode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, promocode) { 
        obj['promocode'] = promocode;
    }

    /**
     * Constructs a <code>PromoOffersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PromoOffersRequest} obj Optional instance to populate.
     * @return {module:model/PromoOffersRequest} The populated <code>PromoOffersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromoOffersRequest();

            if (data.hasOwnProperty('promocode')) {
                obj['promocode'] = ApiClient.convertToType(data['promocode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} promocode
 */
PromoOffersRequest.prototype['promocode'] = undefined;






export default PromoOffersRequest;

