/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BonusProductData from './BonusProductData';
import BonusProducts from './BonusProducts';
import MoneyDiscount from './MoneyDiscount';
import PercentDiscount from './PercentDiscount';

/**
 * The PromoOfferDataResponse model module.
 * @module model/PromoOfferDataResponse
 * @version 1.0
 */
class PromoOfferDataResponse {
    /**
     * Constructs a new <code>PromoOfferDataResponse</code>.
     * @alias module:model/PromoOfferDataResponse
     * @implements module:model/MoneyDiscount
     * @implements module:model/PercentDiscount
     * @implements module:model/BonusProducts
     * @param offerType {module:model/PromoOfferDataResponse.OfferTypeEnum} 
     */
    constructor(offerType) { 
        MoneyDiscount.initialize(this, offerType);PercentDiscount.initialize(this, offerType);BonusProducts.initialize(this, offerType);
        PromoOfferDataResponse.initialize(this, offerType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, offerType) { 
        obj['offerType'] = offerType;
    }

    /**
     * Constructs a <code>PromoOfferDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PromoOfferDataResponse} obj Optional instance to populate.
     * @return {module:model/PromoOfferDataResponse} The populated <code>PromoOfferDataResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromoOfferDataResponse();
            MoneyDiscount.constructFromObject(data, obj);
            PercentDiscount.constructFromObject(data, obj);
            BonusProducts.constructFromObject(data, obj);

            if (data.hasOwnProperty('discountValue')) {
                obj['discountValue'] = ApiClient.convertToType(data['discountValue'], 'Number');
            }
            if (data.hasOwnProperty('offerType')) {
                obj['offerType'] = ApiClient.convertToType(data['offerType'], 'String');
            }
            if (data.hasOwnProperty('discountPercent')) {
                obj['discountPercent'] = ApiClient.convertToType(data['discountPercent'], 'Number');
            }
            if (data.hasOwnProperty('bonusProducts')) {
                obj['bonusProducts'] = ApiClient.convertToType(data['bonusProducts'], [BonusProductData]);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} discountValue
 */
PromoOfferDataResponse.prototype['discountValue'] = undefined;

/**
 * @member {module:model/PromoOfferDataResponse.OfferTypeEnum} offerType
 */
PromoOfferDataResponse.prototype['offerType'] = undefined;

/**
 * @member {Number} discountPercent
 */
PromoOfferDataResponse.prototype['discountPercent'] = undefined;

/**
 * @member {Array.<module:model/BonusProductData>} bonusProducts
 */
PromoOfferDataResponse.prototype['bonusProducts'] = undefined;

/**
 * @member {Number} amount
 */
PromoOfferDataResponse.prototype['amount'] = undefined;


// Implement MoneyDiscount interface:
/**
 * @member {Number} discountValue
 */
MoneyDiscount.prototype['discountValue'] = undefined;
/**
 * @member {module:model/MoneyDiscount.OfferTypeEnum} offerType
 */
MoneyDiscount.prototype['offerType'] = undefined;
// Implement PercentDiscount interface:
/**
 * @member {Number} discountPercent
 */
PercentDiscount.prototype['discountPercent'] = undefined;
/**
 * @member {module:model/PercentDiscount.OfferTypeEnum} offerType
 */
PercentDiscount.prototype['offerType'] = undefined;
// Implement BonusProducts interface:
/**
 * @member {Array.<module:model/BonusProductData>} bonusProducts
 */
BonusProducts.prototype['bonusProducts'] = undefined;
/**
 * @member {Number} amount
 */
BonusProducts.prototype['amount'] = undefined;
/**
 * @member {module:model/BonusProducts.OfferTypeEnum} offerType
 */
BonusProducts.prototype['offerType'] = undefined;



/**
 * Allowed values for the <code>offerType</code> property.
 * @enum {String}
 * @readonly
 */
PromoOfferDataResponse['OfferTypeEnum'] = {

    /**
     * value: "MONEY_DISCOUNT"
     * @const
     */
    "MONEY_DISCOUNT": "MONEY_DISCOUNT",

    /**
     * value: "PERCENT_DISCOUNT"
     * @const
     */
    "PERCENT_DISCOUNT": "PERCENT_DISCOUNT",

    /**
     * value: "BONUS_PRODUCTS"
     * @const
     */
    "BONUS_PRODUCTS": "BONUS_PRODUCTS"
};



export default PromoOfferDataResponse;

