/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PromoCodeDto model module.
 * @module model/PromoCodeDto
 * @version 1.0
 */
class PromoCodeDto {
    /**
     * Constructs a new <code>PromoCodeDto</code>.
     * @alias module:model/PromoCodeDto
     */
    constructor() { 
        
        PromoCodeDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PromoCodeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PromoCodeDto} obj Optional instance to populate.
     * @return {module:model/PromoCodeDto} The populated <code>PromoCodeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromoCodeDto();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('minOrderSum')) {
                obj['minOrderSum'] = ApiClient.convertToType(data['minOrderSum'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} value
 */
PromoCodeDto.prototype['value'] = undefined;

/**
 * @member {Number} minOrderSum
 */
PromoCodeDto.prototype['minOrderSum'] = undefined;






export default PromoCodeDto;

