/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimpleBonusAllOf model module.
 * @module model/SimpleBonusAllOf
 * @version 1.0
 */
class SimpleBonusAllOf {
    /**
     * Constructs a new <code>SimpleBonusAllOf</code>.
     * @alias module:model/SimpleBonusAllOf
     */
    constructor() { 
        
        SimpleBonusAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SimpleBonusAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimpleBonusAllOf} obj Optional instance to populate.
     * @return {module:model/SimpleBonusAllOf} The populated <code>SimpleBonusAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleBonusAllOf();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} productId
 */
SimpleBonusAllOf.prototype['productId'] = undefined;






export default SimpleBonusAllOf;

