/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimpleProductResponse model module.
 * @module model/SimpleProductResponse
 * @version 1.0
 */
class SimpleProductResponse {
    /**
     * Constructs a new <code>SimpleProductResponse</code>.
     * @alias module:model/SimpleProductResponse
     */
    constructor() { 
        
        SimpleProductResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SimpleProductResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimpleProductResponse} obj Optional instance to populate.
     * @return {module:model/SimpleProductResponse} The populated <code>SimpleProductResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleProductResponse();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} displayName
 */
SimpleProductResponse.prototype['displayName'] = undefined;

/**
 * @member {String} description
 */
SimpleProductResponse.prototype['description'] = undefined;

/**
 * @member {String} imageUrl
 */
SimpleProductResponse.prototype['imageUrl'] = undefined;

/**
 * @member {Number} id
 */
SimpleProductResponse.prototype['id'] = undefined;

/**
 * @member {Number} price
 */
SimpleProductResponse.prototype['price'] = undefined;

/**
 * @member {String} meta
 */
SimpleProductResponse.prototype['meta'] = undefined;






export default SimpleProductResponse;

