/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BonusProductData from './BonusProductData';
import SimpleBonusAllOf from './SimpleBonusAllOf';

/**
 * The SimpleBonus model module.
 * @module model/SimpleBonus
 * @version 1.0
 */
class SimpleBonus {
    /**
     * Constructs a new <code>SimpleBonus</code>.
     * @alias module:model/SimpleBonus
     * @extends module:model/BonusProductData
     * @implements module:model/BonusProductData
     * @implements module:model/SimpleBonusAllOf
     * @param productType {module:model/SimpleBonus.ProductTypeEnum} 
     */
    constructor(productType) { 
        BonusProductData.initialize(this, productType);SimpleBonusAllOf.initialize(this);
        SimpleBonus.initialize(this, productType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productType) { 
    }

    /**
     * Constructs a <code>SimpleBonus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimpleBonus} obj Optional instance to populate.
     * @return {module:model/SimpleBonus} The populated <code>SimpleBonus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleBonus();
            BonusProductData.constructFromObject(data, obj);
            BonusProductData.constructFromObject(data, obj);
            SimpleBonusAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} productId
 */
SimpleBonus.prototype['productId'] = undefined;


// Implement BonusProductData interface:
/**
 * @member {module:model/BonusProductData.ProductTypeEnum} productType
 */
BonusProductData.prototype['productType'] = undefined;
// Implement SimpleBonusAllOf interface:
/**
 * @member {Number} productId
 */
SimpleBonusAllOf.prototype['productId'] = undefined;




export default SimpleBonus;

