/**
 * Pizza Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PizzaShopApi);
  }
}(this, function(expect, PizzaShopApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PizzaShopApi.CheckoutRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CheckoutRequest', function() {
    it('should create an instance of CheckoutRequest', function() {
      // uncomment below and update the code to test CheckoutRequest
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be.a(PizzaShopApi.CheckoutRequest);
    });

    it('should have the property cityId (base name: "cityId")', function() {
      // uncomment below and update the code to test the property cityId
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property promoCode (base name: "promoCode")', function() {
      // uncomment below and update the code to test the property promoCode
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property addressId (base name: "addressId")', function() {
      // uncomment below and update the code to test the property addressId
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property payment (base name: "payment")', function() {
      // uncomment below and update the code to test the property payment
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property products (base name: "products")', function() {
      // uncomment below and update the code to test the property products
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

    it('should have the property bonusProducts (base name: "bonusProducts")', function() {
      // uncomment below and update the code to test the property bonusProducts
      //var instance = new PizzaShopApi.CheckoutRequest();
      //expect(instance).to.be();
    });

  });

}));
